// Generated by CoffeeScript 1.12.2
(function() {
  var Popup,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  module.exports = Popup = (function() {
    function Popup() {
      this.keydown = bind(this.keydown, this);
      this.setPositionRelative = bind(this.setPositionRelative, this);
      this.setPositionAbsolute = bind(this.setPositionAbsolute, this);
      this.removeKeydownEvent = bind(this.removeKeydownEvent, this);
      this.setKeydownEvent = bind(this.setKeydownEvent, this);
      this.hide = bind(this.hide, this);
      this.show = bind(this.show, this);
    }

    Popup.prototype.view = __dirname;

    Popup.prototype.name = 'k-popup';

    Popup.prototype.destroy = function() {
      return this.removeKeydownEvent();
    };

    Popup.prototype.create = function() {
      var element;
      this.model.set('top', 'auto');
      this.model.set('right', 'auto');
      this.model.set('marginleft', '0');
      element = this.model.get('element');
      this.el = element ? document.getElementById(element) : this.popup.parentNode;
      if (this.el) {
        return this.el.addEventListener('click', this.show, false);
      }
    };

    Popup.prototype.show = function(e) {
      if (!this.model.get('show') && this.el && e) {
        e.preventDefault();
        e.stopPropagation();
        if (this.model.get('absolute')) {
          this.setPositionAbsolute();
        } else {
          this.setPositionRelative();
        }
        this.model.set('show', true);
        return this.setKeydownEvent();
      }
    };

    Popup.prototype.hide = function(e) {
      var h;
      h = (function(_this) {
        return function() {
          _this.model.del('show');
          return _this.model.del('hiding');
        };
      })(this);
      this.removeKeydownEvent();
      return this.model.set('hiding', true, function() {
        return setTimeout(h, 310);
      });
    };

    Popup.prototype.setKeydownEvent = function() {
      return document.addEventListener('keydown', this.keydown, true);
    };

    Popup.prototype.removeKeydownEvent = function() {
      return document.removeEventListener('keydown', this.keydown);
    };

    Popup.prototype.setPositionAbsolute = function() {
      var rect, right;
      rect = this.el.getBoundingClientRect();
      this.model.set('top', rect.bottom + 10 + 'px');
      right = rect.right + 125 > window.innerWidth ? 10 : window.innerWidth - rect.right - 125;
      return this.model.set('right', right + 'px');
    };

    Popup.prototype.setPositionRelative = function() {
      var marginleft, rect;
      rect = this.el.getBoundingClientRect();
      marginleft = rect.right + 125 > window.innerWidth ? -125 - (rect.right + 125 - window.innerWidth) - 10 : -125;
      return this.model.set('marginleft', marginleft + 'px');
    };

    Popup.prototype.keydown = function(e) {
      var key;
      key = e.keyCode || e.which;
      if (key === 27) {
        return this.hide();
      }
    };

    return Popup;

  })();

}).call(this);
