// Generated by CoffeeScript 1.9.0
(function() {
  var Popup,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  module.exports = Popup = (function() {
    function Popup() {
      this.keydown = __bind(this.keydown, this);
      this.resize = __bind(this.resize, this);
      this.setPosition = __bind(this.setPosition, this);
      this.hide = __bind(this.hide, this);
      this.show = __bind(this.show, this);
    }

    Popup.prototype.view = __dirname;

    Popup.prototype.name = 'k-popup';

    Popup.prototype.create = function() {
      var elId;
      elId = this.model.get('element');
      if (elId) {
        this.el = document.getElementById(elId);
        if (this.el) {
          return this.el.addEventListener('click', this.show, false);
        }
      }
    };

    Popup.prototype.show = function(e) {
      if (this.el && e) {
        e.preventDefault();
        e.stopPropagation();
        window.addEventListener('resize', this.resize, false);
        this.setPosition();
        return this.model.set('show', true);
      }
    };

    Popup.prototype.hide = function(e) {
      var h;
      h = (function(_this) {
        return function() {
          _this.model.del('leftborder');
          _this.model.del('show');
          return _this.model.del('hiding');
        };
      })(this);
      window.removeEventListener('resize', this.resize);
      return this.model.set('hiding', true, function() {
        return setTimeout(h, 310);
      });
    };

    Popup.prototype.setPosition = function() {
      var left, rect;
      rect = this.el.getBoundingClientRect();
      this.model.set('top', rect.bottom + 10);
      left = (rect.left + (rect.width / 2)) - 125;
      if (left < 0) {
        left = 10;
        this.model.set('leftborder', 'leftborder');
      } else {
        this.model.del('leftborder');
      }
      return this.model.set('left', left);
    };

    Popup.prototype.resize = function(e) {
      return this.setPosition();
    };

    Popup.prototype.keydown = function(e) {
      var key;
      key = e.keyCode || e.which;
      if (key === 27) {
        return this.hide();
      }
    };

    return Popup;

  })();

}).call(this);
